title: George Soteriou
email: george@soteriou.me
description: >- # this means to ignore newlines until "baseurl:"
  George Soteriou's Home
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://georgesoteriou.com"                                             

# Build settings
plugins:
  - jekyll-feed

projects: [
  "DoCSoc-webmaster-vote-me-website-2018",
  "Blaze-Racing-Team",
  "Tree-grow-sketch",
  "Dice-roll",
  "rockets-genetic-algorithm",
  "Circles-sketch",
  "Binary-Clock",
  "Neural-Network-Classifier-sketch-JS",
  "NIM",
  "Racaman-Sequence"
]